-- MySQL Script generated by MySQL Workbench
-- Sun 14 Apr 2024 06:00:20 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Planejamente
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Planejamente
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Planejamente` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Planejamente` ;

-- -----------------------------------------------------
-- Table `Planejamente`.`Acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`Acesso` (
  `id` INT NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  `Salt` VARCHAR(45) NULL,
  `GoogleOAuthToken` VARCHAR(45) NULL,
  `dtCriacao` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Planejamente`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`Usuario` (
  `id` CHAR(36) NOT NULL,
  `Nome` VARCHAR(255) NOT NULL,
  `DataDeNascimento` DATE NOT NULL,
  `Telefone` VARCHAR(255) NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  `dtCriacao` DATETIME NOT NULL,
  `Acesso` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Usuario_Acesso1_idx` (`Acesso` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Acesso1`
    FOREIGN KEY (`Acesso`)
    REFERENCES `Planejamente`.`Acesso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Planejamente`.`Psicologo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`Psicologo` (
  `id` CHAR(36) NOT NULL,
  `CRP` VARCHAR(45) NULL,
  `CNPJ` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `Usuario` CHAR(36) NOT NULL,
  `Tratamento` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Psicólogo_Usuario1_idx` (`Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Psicólogo_Usuario1`
    FOREIGN KEY (`Usuario`)
    REFERENCES `Planejamente`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Planejamente`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`Paciente` (
  `id` INT NOT NULL,
  `Usuario` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Paciente_Usuario1_idx` (`Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_Usuario1`
    FOREIGN KEY (`Usuario`)
    REFERENCES `Planejamente`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Planejamente`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`Consulta` (
  `id` CHAR(36) NOT NULL,
  `DataHoraInicio` DATETIME NOT NULL,
  `DataHoraFim` DATETIME NOT NULL,
  `Status` VARCHAR(255) NOT NULL,
  `Observacoes` VARCHAR(255) NOT NULL,
  `Psicologo` CHAR(36) NOT NULL,
  `Link` VARCHAR(255) NOT NULL,
  `Paciente` INT NOT NULL,
  `dtCriacao` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `Psicólogo` (`Psicologo` ASC) VISIBLE,
  INDEX `fk_Consulta_Paciente1_idx` (`Paciente` ASC) VISIBLE,
  CONSTRAINT `Consulta_ibfk_2`
    FOREIGN KEY (`Psicologo`)
    REFERENCES `Planejamente`.`Psicologo` (`id`),
  CONSTRAINT `fk_Consulta_Paciente1`
    FOREIGN KEY (`Paciente`)
    REFERENCES `Planejamente`.`Paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Planejamente`.`Arquivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`Arquivos` (
  `id` CHAR(36) NOT NULL,
  `Url` VARCHAR(255) NOT NULL,
  `Consulta` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Consulta` (`Consulta` ASC) VISIBLE,
  CONSTRAINT `Arquivos_ibfk_1`
    FOREIGN KEY (`Consulta`)
    REFERENCES `Planejamente`.`Consulta` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Planejamente`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`Avaliacao` (
  `id` CHAR(36) NOT NULL,
  `Consulta` CHAR(36) NOT NULL,
  `Descricao` VARCHAR(255) NOT NULL,
  `Nota` DECIMAL(2,1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Consulta` (`Consulta` ASC) VISIBLE,
  CONSTRAINT `Avaliação_ibfk_1`
    FOREIGN KEY (`Consulta`)
    REFERENCES `Planejamente`.`Consulta` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Planejamente`.`Especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`Especialidade` (
  `id` CHAR(36) NOT NULL,
  `Descricao` VARCHAR(255) NOT NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Planejamente`.`EspecialidadePsicologo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`EspecialidadePsicologo` (
  `id` CHAR(36) NOT NULL,
  `Especialidade` CHAR(36) NOT NULL,
  `Psicologo` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Especialidade` (`Especialidade` ASC) VISIBLE,
  INDEX `Psicólogo` (`Psicologo` ASC) VISIBLE,
  CONSTRAINT `EspecialidadePsicólogo_ibfk_1`
    FOREIGN KEY (`Especialidade`)
    REFERENCES `Planejamente`.`Especialidade` (`id`),
  CONSTRAINT `EspecialidadePsicólogo_ibfk_2`
    FOREIGN KEY (`Psicologo`)
    REFERENCES `Planejamente`.`Psicologo` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Planejamente`.`ExperienciaFormacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`ExperienciaFormacao` (
  `id` CHAR(36) NOT NULL,
  `DataInicio` DATE NOT NULL,
  `DataFim` DATE NULL DEFAULT NULL,
  `Instituicao` VARCHAR(255) NOT NULL,
  `Cargo` VARCHAR(255) NULL,
  `Descricao` VARCHAR(255) NOT NULL,
  `Psicologo` CHAR(36) NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Titulo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `Psicólogo` (`Psicologo` ASC) VISIBLE,
  CONSTRAINT `Experiência_ibfk_1`
    FOREIGN KEY (`Psicologo`)
    REFERENCES `Planejamente`.`Psicologo` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Planejamente`.`Agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`Agenda` (
  `id` CHAR(36) NOT NULL,
  `Dia` VARCHAR(15) NULL,
  `horaInicio` TIME NULL,
  `horaFim` TIME NULL,
  `Psicologo` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Agenda_Psicologo1_idx` (`Psicologo` ASC) VISIBLE,
  CONSTRAINT `fk_Agenda_Psicologo1`
    FOREIGN KEY (`Psicologo`)
    REFERENCES `Planejamente`.`Psicologo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
