-- MySQL Script generated by MySQL Workbench
-- Thu 04 Apr 2024 08:22:12 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Planejamente
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Planejamente
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Planejamente` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Planejamente` ;

-- -----------------------------------------------------
-- Table `Planejamente`.`Psicólogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`Psicólogo` (
  `id` CHAR(36) NOT NULL,
  `CRP` VARCHAR(45) NULL,
  `CNPJ` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Planejamente`.`Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`Endereço` (
  `id` CHAR(36) NOT NULL,
  `Número` INT NOT NULL,
  `CEP` CHAR(8) NOT NULL,
  `Rua` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Planejamente`.`Usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`Usuário` (
  `id` CHAR(36) NOT NULL,
  `Nome` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Sal` VARCHAR(255) NOT NULL,
  `Senha` VARCHAR(255) NOT NULL,
  `DataDeNascimento` DATE NOT NULL,
  `Telefone` VARCHAR(255) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL COMMENT 'O usuario só pode ter 1 pscicologo ou varios ? qual a regra de negocio ai',
  `Psicólogo_id` CHAR(36) NULL,
  `Endereço` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Endereço` (`Endereço` ASC) VISIBLE,
  INDEX `fk_Usuário_Psicólogo1_idx` (`Psicólogo_id` ASC) VISIBLE,
  CONSTRAINT `Paciente_ibfk_10`
    FOREIGN KEY (`Endereço`)
    REFERENCES `Planejamente`.`Endereço` (`id`),
  CONSTRAINT `fk_Usuário_Psicólogo1`
    FOREIGN KEY (`Psicólogo_id`)
    REFERENCES `Planejamente`.`Psicólogo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Planejamente`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`Consulta` (
  `id` CHAR(36) NOT NULL,
  `DataHoraInicio` DATETIME NOT NULL,
  `DataHoraFim` DATETIME NOT NULL,
  `Status` VARCHAR(255) NOT NULL,
  `Observações` VARCHAR(255) NOT NULL,
  `Psicólogo_id` CHAR(36) NOT NULL,
  `Link` VARCHAR(255) NOT NULL,
  `Usuário_id` CHAR(36) NOT NULL,
  `Avalia;'ao` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `Psicólogo` (`Psicólogo_id` ASC) VISIBLE,
  INDEX `fk_Consulta_Usuário1_idx` (`Usuário_id` ASC) VISIBLE,
  CONSTRAINT `Consulta_ibfk_2`
    FOREIGN KEY (`Psicólogo_id`)
    REFERENCES `Planejamente`.`Psicólogo` (`id`),
  CONSTRAINT `fk_Consulta_Usuário1`
    FOREIGN KEY (`Usuário_id`)
    REFERENCES `Planejamente`.`Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Planejamente`.`Arquivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`Arquivos` (
  `id` CHAR(36) NOT NULL,
  `Url` VARCHAR(255) NOT NULL,
  `Nome` VARCHAR(255) NOT NULL,
  `Tamanho` INT NOT NULL,
  `Extensão` VARCHAR(255) NOT NULL,
  `Consulta_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Consulta` (`Consulta_id` ASC) VISIBLE,
  CONSTRAINT `Arquivos_ibfk_1`
    FOREIGN KEY (`Consulta_id`)
    REFERENCES `Planejamente`.`Consulta` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Planejamente`.`Especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`Especialidade` (
  `id` CHAR(36) NOT NULL,
  `Descrição` VARCHAR(255) NOT NULL,
  `Título` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Planejamente`.`EspecialidadePsicólogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`EspecialidadePsicólogo` (
  `id` CHAR(36) NOT NULL,
  `Especialidade_id` CHAR(36) NOT NULL,
  `Psicólogo_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Especialidade` (`Especialidade_id` ASC) VISIBLE,
  INDEX `Psicólogo` (`Psicólogo_id` ASC) VISIBLE,
  CONSTRAINT `EspecialidadePsicólogo_ibfk_1`
    FOREIGN KEY (`Especialidade_id`)
    REFERENCES `Planejamente`.`Especialidade` (`id`),
  CONSTRAINT `EspecialidadePsicólogo_ibfk_2`
    FOREIGN KEY (`Psicólogo_id`)
    REFERENCES `Planejamente`.`Psicólogo` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Planejamente`.`Experiência_Formação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Planejamente`.`Experiência_Formação` (
  `id` CHAR(36) NOT NULL,
  `DataInicio` DATE NOT NULL,
  `DataFim` DATE NULL DEFAULT NULL,
  `Instituição` VARCHAR(255) NOT NULL,
  `Cargo` VARCHAR(255) NULL,
  `Descrição` VARCHAR(255) NOT NULL,
  `Psicólogo_id` CHAR(36) NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Título` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `Psicólogo` (`Psicólogo_id` ASC) VISIBLE,
  CONSTRAINT `Experiência_ibfk_1`
    FOREIGN KEY (`Psicólogo_id`)
    REFERENCES `Planejamente`.`Psicólogo` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
