name: Tofu apply

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: "Configure AWS Credentials Action for GitHub Actions"
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    # Restore cached Terraform state if available
    - name: Restore Terraform state
      id: cache-state
      uses: actions/cache@v3
      with:
        path: ./tf/terraform.tfstate
        key: terraform-state-${{ github.ref }}
        restore-keys: terraform-state-

    - uses: opentofu/setup-opentofu@v1

    - name: Tofu Init
      working-directory: ./tf
      run: tofu init

    - id: plan  
      working-directory: ./tf
      run: tofu apply -auto-approve

    - name: Upload Terraform state
      uses: actions/upload-artifact@v4
      with:
        name: terraform-state
        path: ./tf/terraform.tfstate
        compression-level: 0  # No compression for faster upload

    - name: Echo output of plan
      run: echo ${{ steps.plan.outputs.stdout }}

    - name: Echo output of stderr
      run: echo ${{ steps.plan.outputs.stderr }}

    - name: Echo exit code
      run: echo ${{ steps.plan.outputs.exitcode }}
