name: Tofu destroy

on:
  workflow_dispatch:

jobs:

  destroy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: "Configure AWS Credentials Action for GitHub Actions"
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    # Baixar o Terraform state artifact salvo no workflow anterior
    - uses: actions/download-artifact@v4
      with:
        name: terraform-state  # Nome do artefato salvo anteriormente
        path: ./tf

    - name: Verificar estrutura dos arquivos baixados
      run: ls -R ./tf

    - uses: opentofu/setup-opentofu@v1

    - name: Tofu Init
      working-directory: ./tf
      run: tofu init

    - name: Tofu Destroy
      working-directory: ./tf
      run: tofu destroy -auto-approve
